### ISSUE TITLE
Build in xcode

### ISSUE THREAD

**Issue by rationalpickle** [nod/rokumote#5]
Thank you for your work on this. 

Yes, we know how to Github, but can you please elaborate as to how I can build this thing?

**Comment by nod** [comment]
Hi there.  I haven't touched this codebase in a while (been running on my laptop quite happily).

Give me a few days to dig into this and make sure it's still good for swift 3 and I'll add a few instructions.  

There are also releases that I prebuilt if you'd like to use one of those.

You can find those here:  https://github.com/nod/rokumote/releases

**Comment by rationalpickle** [comment]
Thank you for the reply. Prebuilt option sounds good. I'll check it out.
