### ISSUE TITLE
Doesn't seem to actually work at all?

### ISSUE THREAD

**Issue by MikeRich88** [nod/rokumote#8]
It found my Roku's IP address, but none of the buttons actually do anything at all.

The official Roku app for iPhone works, but has it's own immensely stupid issues.

Also, my Roku crashed and rebooted literally while writing the previous sentence, so maybe my Roku is just a POS.

**Comment by nod** [comment]
Hey!  So sorry for the slow reply.  Somehow missed this notification. I'll give the app a try this weekend and see what's going on.

**Comment by nod** [comment]
Just installed latest version on a clean laptop build I had here.  "Mostly" seemed to work well (clicking to type and the quick links drop down both didn't work) but all the other functionality worked well.  

@MikeRich88 I have actually seen it detect a different roku in the house if you have two and appear unresponsive.  Is it possible this happened?

Closing this tix.
